---

- name: set global name
  git_config:
    name: user.name
    scope: global
    value: "{{ git.global_name }}"

- name: set global email
  git_config:
    name: user.email
    scope: global
    value: "{{ git.global_email }}"

- name: copy github key
  copy:
    src: ./secret/github
    dest: ~/.ssh/id_rsa
    owner: root
    group: root
    mode: 0600
