---
- hosts: all
  # gather_facts: no

  # pre_tasks:
  #   - debug: 
  #       msg: "locale incorrect"
  #     when: ansible_env.LC_ALL != "en_US.UTF-8"

  vars_files:
    - "vars/settings.vars.yml"


  roles:
    - role: setlocale
      when: ansible_env.LC_ALL != "en_US.UTF-8"
      tags:
        - setlocale

    - role: common
      tags:
        - common

    - role: users
      tags:
        - users

    - role: nginx
      tags:
        - nginx
        - php

    - role: nodejs
      tags:
        - nodejs
        - rails
    
    - role: php
      tags:
        - php
    
    - role: mysql
      tags:
        - mysql
        - php