---

- name: docker - add apt keys
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: docker - add repos
  apt_repository: 
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: docker - install packages
  apt:
    name: docker-ce
