---

- include: nodejs.yml
- include: oh-my-zsh.yml
- include: docker.yml
- include: rails.yml
- include: php.yml

- name: install packages
  apt:
    name: "{{ item }}"
  with_items:
    - tree
    - tmux
    - vim
  tags:
    - packages
    