---

# - include: nodejs.yml
# - include: docker.yml
# - include: rails.yml
# - include: php.yml
# - include: nginx.yml

# - name: install packages
#   apt:
#     name: "{{ item }}"
#   with_items:
#     - tree
#     - tmux
#     - vim
#   tags:
#     - packages
    