---

- name: add key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
  tags:
    - nginx

- name: add repo
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx
  tags:
    - nginx

- name: install nginx
  apt: 
    name: nginx
  tags:
    - nginx
