---

- name: add repository
  apt_repository: 
    repo: ppa:ondrej/php
  tags:
    - php

- name: install php
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php
    - php-cli
    - php-intl
  tags:
    - php

- name: install composer
  shell: |
    cd /tmp/
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    mv /tmp/composer.phar /usr/local/bin/composer
  tags:
    - php

- name: install composer addons
  shell: "composer global require {{ item }}"
  with_items:
    - "squizlabs/php_codesniffer=*"
    - "mkusher/padawan=*"
  become: true
  become_user: "{{ user.name }}"
  tags:
    - php
