---

- name: install ruby
  apt:
    name: "{{ item }}"
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
    - ruby
    - ruby-dev
  tags:
    - rails

- name: add gem bin folder to path
  shell: ruby -e 'print Gem.user_dir'
  become: true
  become_user: "{{ user.name }}"
  register: gem_bin_path
  tags:
    - rails

- name: install gems
  gem:
    name: "{{ item }}"
    state: latest
  # ignore_errors: yes
  register: gems_obj
  with_items:
    - rails
    - rake
    - rubocop
  become: true
  become_user: "{{ user.name }}"
  environment:
    PATH: "{{ gem_bin_path.stdout}}/bin:{{ ansible_env.PATH }}"
  tags:
    - rails

# - name: debug
#   debug:
#     msg: "{{ gems_obj }}"
