---

- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y

- name: upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: generate locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: set locale
  become: true
  shell: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8

- name: reboot host
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait to host up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 10
    timeout: 300
  connection: local
