---

- name: get dot files from github
  git:
    repo: "{{ git.dotfiles_repo }}"
    dest: ~/dotfiles
    accept_hostkey: true

- name: copy dot files
  block:
    - shell: ls ~/dotfiles/files/
      register: path_files
    - file:
        src: "~/dotfiles/files/{{ item }}"
        dest: "~/.{{ item }}"
        state: link
      with_items: "{{ path_files.stdout_lines }}"
