---

- name: get dot files from github
  git:
    repo: "{{ git.dotfiles_repo }}"
    dest: "{{ user.home }}/dotfiles"
    accept_hostkey: true
  tags:
    - dotfiles

- name: copy dot files
  block:
    - shell: "ls {{ user.home }}/dotfiles/files/"
      register: path_files
    - file:
        src: "{{ user.home }}/dotfiles/files/{{ item }}"
        dest: "{{ user.home }}/.{{ item }}"
        state: link
        force: yes
      with_items: "{{ path_files.stdout_lines }}"
  tags:
    - dotfiles
    
- name: delete oh-my-zsh custom
  file:
    dest: "{{ user.home }}/.oh-my-zsh/custom"
    state: absent
  tags:
    - dotfiles
    

- name: link oh-my-zsh customs
  file:
    src: "{{ user.home }}/dotfiles/oh-my-zsh/custom"
    dest: "{{ user.home }}/.oh-my-zsh/custom"
    state: link
    force: yes
  tags:
    - dotfiles
     