---


- name: get dot files from github
  git:
    repo: git@github.com:CountJr/dot-files.git
    dest: ~/.dot-files

- name: copy dot files
  block:
    - shell: ls ~/.dot-files/files/
      register: path_files
    - copy:
        src: "~/.dot-files/files/{{ item }}"
        dest: "~/.{{ item }}"
        remote_src: yes
      with_items: "{{ path_files.stdout_lines }}"
