---

# - name: install mono - repo
#   apt_repository: 
#     repo: deb http://download.mono-project.com/repo/ubuntu xenial main
    
# - name: install mono
#   shell: |
#     apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
#     echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/mono-official.list

# - name: install dependencies
#   apt:
#     name: "{{ item }}"
#     allow_unauthenticated: yes
#   with_items:
#     - mono-devel
#     - cmake
#     - build-essential
#     - python-dev
#     - python3-dev
#     - mono-runtime
#     - mono-xbuild
#     - golang
#     - cargo

- name: get dot files from github
  git:
    repo: "{{ users_dotfiles_repo }}"
    dest: "{{ user.home }}/dotfiles"
    accept_hostkey: true
    key_file: "{{ user.home }}/.ssh/id_rsa"
    force: yes
  become: true
  become_user: "{{ user.name }}"

- name: copy dot files
  block:
    - shell: "ls {{ user.home }}/dotfiles/files/"
      register: path_files
    - file:
        src: "{{ user.home }}/dotfiles/files/{{ item }}"
        dest: "{{ user.home }}/.{{ item }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"  
        state: link
        force: yes
      with_items: "{{ path_files.stdout_lines }}"
    
- name: delete oh-my-zsh custom
  file:
    dest: "{{ user.home }}/.oh-my-zsh/custom"
    state: absent
    

- name: link oh-my-zsh customs
  file:
    src: "{{ user.home }}/dotfiles/oh-my-zsh/custom"
    dest: "{{ user.home }}/.oh-my-zsh/custom"
    state: link
    force: yes

- name: oh-my-zsh - change shell to zsh
  shell: "chsh -s /bin/zsh {{ user.name }}"

# - name: create dir for vim-plug
#   file:
#     path: ~/.vim/autoload/
#     state: directory
#     recurse: yes
#   become: true
#   become_user: "{{ user.name }}"

# - name: download vim-plug
#   get_url:
#     url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#     dest: ~/.vim/autoload/plug.vim
#   become: true
#   become_user: "{{ user.name }}"

# - name: install vim plugins
#   shell: |
#     vim -E -s -c "source ~/.vimrc" +PlugInstall +qall -V
#   become: true
#   become_user: "{{ user.name }}"
  # ignore_errors: yes
  # register: test_obj

# - name: debug
#   debug:
#     msg: "{{ test_obj.start }}\n{{ test_obj.end }}\n{{ test_obj.delta }}"
#   tags:
#     - dotfiles

# - name: initialize YouCompleteMe
#   shell: |
#     cd ~/.vim/plugged/YouCompleteMe
#     git submodule update --init --recursive
#     ./install.py --all
#   become: true
#   become_user: "{{ user.name }}"
#   ignore_errors: yes
#   register: test_obj
#   tags:
#     - dotfiles

# - name: debug
#   debug:
#     msg: "{{ test_obj }}\n{{ test_obj.end }}\n{{ test_obj.delta }}"
#   tags:
#     - dotfiles