---

- name: set global name
  git_config:
    name: user.name
    scope: global
    value: "{{ users_git_global_name }}"

- name: set global email
  git_config:
    name: user.email
    scope: global
    value: "{{ users_git_global_email }}"

- name: copy github key
  copy:
    src: ./secret/github
    dest: "{{ user.home }}/.ssh/id_rsa"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
