---

# - name: make group
#   group:
#     name: super
#     state: present
# tags:
#   - all
#   - users

# - name: delete user {{ name }}
#   user:
#     name: count
#     state: absent
#     remove: yes
# tags:
#   - all
#   - users

- name: "create user {{ user.name }}"
  user:
    name: "{{ user.name }}"
    # groups: super
    shell: /bin/bash
  register: user
  tags:
    - all
    - users

- name: set authorized key
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags:
    - all
    - users

