---

- name: oh-my-zsh - install packages
  apt:
    name: zsh

- name: oh-my-zsh - install oh-my-zsh
  git:
    repo: "{{ users_ohmyzsh_repository }}"
    dest: "{{ user.home }}/.oh-my-zsh"
    force: yes
    key_file: "{{ user.home }}/.ssh/id_rsa"
  become: true
  become_user: "{{ user.name }}"

# - name: oh-my-zsh - copy config file
#   copy:
#     src: "{{ user.home }}/.oh-my-zsh/templates/zshrc.zsh-template"
#     dest: "{{ user.home }}/.zshrc"
#     owner: "{{ user.name }}"
#     group: "{{ user.name }}"
#     mode: 0644
#     remote_src: yes

