---

- name: fix an aptitude error, found in ubuntu 16.04 lts
  apt:
    name: "{{ item }}"
  with_items: "{{ common_aptitude_fix_packages }}"

- name: upgrade
  apt:
    upgrade: "{{ common_upgrade_method }}"
    update_cache: yes
    cache_valid_time: 86400

- name: install common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ common_packages_list }}"
