---

- name: add repository
  apt_repository: 
    repo: ppa:ondrej/php

- name: install php
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php7.1-fpm
    - php7.1-cli
    - php7.1-intl
    - php7.1-zip
    - php7.1-mysql

- name: check composer install
  stat: "path=/usr/local/bin/composer"
  register: composer_bin

- name: install composer
  block:
    - name: download composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755
    - name: run composer installer
      shell: |
        php /tmp/composer-installer.php --install-dir /tmp
        cd /tmp
    - name: copy composer executable to bin folder
      copy:
        src: /tmp/composer.phar
        dest: /usr/local/bin/composer
        remote_src: true
        mode: 0755
    - name: install composer addons
      shell: "composer global require {{ item }}"
      with_items:
        - "squizlabs/php_codesniffer=*"
        - "mkusher/padawan=*"
      ignore_errors: yes
      become: true
      become_user: "{{ user.name }}"
    - name: delete temp files
      file:
        path: "/tmp/{{ item }}"
        state: absent
      with_items:
        - composer-installer.php
        - composer.phar
  when: not composer_bin.stat.exists

# - name: install composer
#   shell: |
#     cd /tmp/
#     php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#     php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
#     php composer-setup.php
#     php -r "unlink('composer-setup.php');"
#     mv /tmp/composer.phar /usr/local/bin/composer


